SHELL=/bin/sh

CFLAGS = -Wall -pedantic -g

EXECUTABLES=	echo_stderr		\
		fgets_sur_fd_4		\
		fgets_fprintf_sur_fd_5	\
		printf_sur_fd_3		\
		write_sur_fd_3		\


all : ${EXECUTABLES}

clean : 
	@rm -f core *.o *.out
	@rm -f ${EXECUTABLES}
